# Generated by Django 6.0.1 on 2026-01-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='AyuBar', max_length=128),
            preserve_default=False,
        ),
    ]
